### ISSUE TITLE
How can I use skin?

### ISSUE THREAD

**Issue by xiaonian233** [kapehh-karen/Minecraft-Yggdrasil-Authorization#1]
How can I use skin?

**Comment by kapehh-karen** [comment]
In table `kph_players` set http url (example: https://i.imgur.com/1Y0KtKO.png) to field `skin`.

Next Step (only for OptiFine):
Run Wireshark and find optifine skin url. Then find it url in optifine.jar and make invalide url, optifine can't load skin with invalid url.

**Comment by xiaonian233** [comment]
May I patch authlib to let it work?

**Comment by kapehh-karen** [comment]
Of course.
Compile file YggdrasilMinecraftSessionService.java and result *.class files replace in authlib.jar (for client) and spigot.jar/craftbukkit.jar/server.jar (for server)

**Comment by xiaonian233** [comment]
I patched it but just auth work,I dont know where I can edit skin url.

**Comment by xiaonian233** [comment]
I mean, I have replaced authlib's account verification and worked very well. I don't know where to make skin work to modify authlib.

**Comment by kapehh-karen** [comment]
For **authlib** necessary modify only `/com/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService.java`

But also need check `hasJoined` request. Look at my `authorization.php` (197 line) there written correctly response for server.

**Comment by xiaonian233** [comment]
I modified these, can't the skin be modified by authlib?

**Comment by kapehh-karen** [comment]
No. Try remove OptiFine from Client.

**Comment by xiaonian233** [comment]
ok，thx

**Comment by kapehh-karen** [comment]
Check without OptiFine and write about the result )
