### ISSUE TITLE
How to use register action in url?

### ISSUE THREAD

**Issue by KlinK123** [kapehh-karen/Minecraft-Yggdrasil-Authorization#2]
How can i register in url?

**Comment by kapehh-karen** [comment]
I do not understand you.
What is "register in url" in you think?

You **Launched** should make request to `/kph/authorization.php?action=register` with two POST params: **username** and **password**

**Comment by KlinK123** [comment]
Yeah thanks, auth works and i patched the spigot but the spigot server say: Internal server error
Why?

**Comment by kapehh-karen** [comment]
Try set `online-mode=false` in server properties

**Comment by kapehh-karen** [comment]
Maybe username is long.
I don't remember how to solve this :( sorry

**Comment by KlinK123** [comment]
okay np, but now server say: Authentication servers down
You know how to solve?

**Comment by kapehh-karen** [comment]
Check connection between minecraft server and authentication server
