### ISSUE TITLE
How to modify spigot authentication server?

### ISSUE THREAD

**Issue by KlinK123** [kapehh-karen/Minecraft-Yggdrasil-Authorization#3]

**Comment by KlinK123** [comment]
how to save file in *.class?
text editor name?

**Comment by kapehh-karen** [comment]
Compile with Java Compiler or use Java IDE (Intellij IDEA Community)

**Comment by KlinK123** [comment]
can you give me a download to Java Compiler? please

**Comment by KlinK123** [comment]
how convert java with Intellij? i save as class but the result file is 0 kb and 0 text

**Comment by kapehh-karen** [comment]
Google
